/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PersonComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface PersonComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PersonComponent': Components.PersonComponent;
  }

  interface StencilIntrinsicElements {
    'person-component': Components.PersonComponentAttributes;
  }


  interface HTMLPersonComponentElement extends Components.PersonComponent, HTMLStencilElement {}
  var HTMLPersonComponentElement: {
    prototype: HTMLPersonComponentElement;
    new (): HTMLPersonComponentElement;
  };

  interface HTMLElementTagNameMap {
    'person-component': HTMLPersonComponentElement
  }

  interface ElementTagNameMap {
    'person-component': HTMLPersonComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
